#!/usr/bin/env python3
"""
GitHub Bounty Hunter --- zi dong sou xun GitHub shang jin Issue bing ti jiao xiu fu PR de zi dong hua gong ju.

yong fa:
    python github_bounty_hunter.py                  # wan zheng yun xing
    python github_bounty_hunter.py --dry-run        # jin sou suo fen xi sheng cheng, bu ti jiao PR
    python github_bounty_hunter.py --limit 5         # zui duo chu li 5 ge issue
    python github_bounty_hunter.py --issue <url>     # dan ge issue

huan jing bian liang:
    GITHUB_TOKEN      GitHub Personal Access Token (bi xu)
    OPENAI_API_KEY    OpenAI API Key (bi xu)

feng xian jing gao:
    zi dong hua ti jiao PR ke neng bei cang ku wei hu zhe shi wei la ji xin xi. qiang lie jian yi chu qi shi yong --dry-run
    mo shi, ren gong shen he sheng cheng de xiu fu dai ma hou zai shou dong ti jiao. qing zai zun shou GitHub fu wu tiao kuan he
    ge cang ku xing wei zhun ze de qian ti xia shi yong ben gong ju.
"""

from __future__ import annotations

import argparse
import base64
import json
import logging
import os
import random
import re
import sys
import textwrap
import time
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple
from urllib.parse import urlparse

import requests
from openai import OpenAI

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger("bounty_hunter")

GITHUB_API_BASE = "https://api.github.com"
USER_AGENT = "GitHub-Bounty-Hunter/1.0"

BOUNTY_SEARCH_QUERIES: List[str] = [
    "label:bounty+state:open+is:issue",
    "bounty+state:open+is:issue",
    "label:\"good first issue\"+state:open+is:issue+label:\"help wanted\"",
    "label:\"help wanted\"+state:open+is:issue+bounty",
    "label:paid+state:open+is:issue",
    "label:reward+state:open+is:issue",
    "\"$\"+state:open+is:issue+label:\"help wanted\"",
]

BOUNTY_CURRENCY_PATTERNS: List[str] = [
    r"\$\s*\d[\d,]*(?:\.\d{1,2})?",
    r"\d[\d,]*(?:\.\d{1,2})?\s*USD",
    r"\d[\d,]*(?:\.\d{1,2})?\s*ETH",
    r"\d[\d,]*(?:\.\d{1,2})?\s*USDC",
    r"\d[\d,]*(?:\.\d{1,2})?\s*USDT",
    r"(?:bounty|reward)\s*:?\s*\$?\s*\d[\d,]*(?:\.\d{1,2})?",
]

BOUNTY_INDICATOR_WORDS: List[str] = [
    "bounty", "reward", "paid", "payment", "prize", "compensation",
    "\U0001f4b0", "\U0001f4b5", "\U0001f4b2", "\U0001fa99", "funded", "pays", "payout",
]

PR_BODY_TEMPLATE = """## Summary

This PR resolves **#{issue_number}**: {issue_title}

## Changes

{changes_summary}

## Bounty Note

According to the bounty mentioned in the original issue, this fix should
be eligible for the associated reward. If you need payment details or
further information, please reach out via the method described in the issue.

---
*This PR was auto-generated by GitHub Bounty Hunter.
Please review carefully --- AI-generated code may contain errors.*
"""

OUTPUT_DIR = "outputs"


class GitHubClient:
    """Encapsulates GitHub REST API v3 operations."""

    def __init__(self, token: str) -> None:
        self.token = token
        self.session = requests.Session()
        self.session.headers.update({
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "User-Agent": USER_AGENT,
            "X-GitHub-Api-Version": "2022-11-28",
        })
        self._rate_limit_remaining = 5000
        self._rate_limit_reset = 0
        self._user_login: Optional[str] = None

    def _update_rate_limit(self, response: requests.Response) -> None:
        self._rate_limit_remaining = int(
            response.headers.get("X-RateLimit-Remaining", self._rate_limit_remaining)
        )
        self._rate_limit_reset = int(
            response.headers.get("X-RateLimit-Reset", self._rate_limit_reset)
        )

    def _wait_if_needed(self) -> None:
        if self._rate_limit_remaining < 10:
            now = int(time.time())
            wait = max(self._rate_limit_reset - now + 2, 1)
            log.warning("Rate limit nearly exhausted, waiting %d seconds...", wait)
            time.sleep(wait)

    def _request(
        self,
        method: str,
        url: str,
        *,
        json_body: Optional[Dict[str, Any]] = None,
        max_retries: int = 3,
    ) -> requests.Response:
        self._wait_if_needed()
        last_exc: Optional[Exception] = None

        for attempt in range(1, max_retries + 1):
            try:
                resp = self.session.request(method, url, json=json_body, timeout=30)
                self._update_rate_limit(resp)

                if resp.status_code == 403 and "rate limit" in resp.text.lower():
                    reset_time = int(resp.headers.get("X-RateLimit-Reset", time.time() + 60))
                    wait = max(reset_time - int(time.time()) + 2, 5)
                    log.warning("Secondary rate limit triggered, waiting %d seconds...", wait)
                    time.sleep(wait)
                    continue

                if resp.status_code >= 500:
                    log.warning("Server error %d, retry %d/%d", resp.status_code, attempt, max_retries)
                    time.sleep(2 ** attempt)
                    continue

                return resp

            except requests.RequestException as exc:
                last_exc = exc
                log.warning("Network error: %s, retry %d/%d", exc, attempt, max_retries)
                time.sleep(2 ** attempt)

        raise RuntimeError(f"Request failed after {max_retries} retries: {last_exc}")

    def get(self, url: str) -> requests.Response:
        return self._request("GET", url)

    def post(self, url: str, body: Dict[str, Any]) -> requests.Response:
        return self._request("POST", url, json_body=body)

    def patch(self, url: str, body: Dict[str, Any]) -> requests.Response:
        return self._request("PATCH", url, json_body=body)

    def put(self, url: str, body: Optional[Dict[str, Any]] = None) -> requests.Response:
        return self._request("PUT", url, json_body=body)

    @property
    def user_login(self) -> str:
        if self._user_login is None:
            resp = self.get(f"{GITHUB_API_BASE}/user")
            resp.raise_for_status()
            self._user_login = resp.json()["login"]
        return self._user_login


def search_bounty_issues(
    gh: GitHubClient,
    limit: int = 20,
    extra_query: Optional[str] = None,
) -> List[Dict[str, Any]]:
    """Search for bounty issues using the GitHub Search API."""
    found: Dict[int, Dict[str, Any]] = {}

    queries = list(BOUNTY_SEARCH_QUERIES)
    if extra_query:
        queries.append(extra_query)

    for query in queries:
        if len(found) >= limit:
            break
        log.info("Searching: %s", query)
        try:
            resp = gh.get(
                f"{GITHUB_API_BASE}/search/issues?q={query}&per_page=30&sort=created&order=desc"
            )
            resp.raise_for_status()
            data = resp.json()
            for item in data.get("items", []):
                found[item["id"]] = item
            log.info("  Found %d candidates (total %d)", len(data.get("items", [])), len(found))
        except Exception as exc:
            log.error("Search failed (%s): %s", query, exc)
        time.sleep(random.uniform(1.0, 3.0))

    issues = list(found.values())[:limit]
    log.info("Total %d candidate issues", len(issues))
    return issues


def extract_bounty_info(text: str) -> Dict[str, Any]:
    """Extract bounty amount and currency from issue text."""
    matches = []
    for pattern in BOUNTY_CURRENCY_PATTERNS:
        for m in re.finditer(pattern, text, re.IGNORECASE):
            matches.append(m.group(0).strip())

    amount = None
    currency = None
    if matches:
        first = matches[0]
        amt_match = re.search(r"\d[\d,]*(?:\.\d+)?", first)
        if amt_match:
            amount = amt_match.group(0).replace(",", "")
        if "$" in first:
            currency = "USD"
        elif "ETH" in first.upper():
            currency = "ETH"
        elif "USDC" in first.upper():
            currency = "USDC"
        elif "USDT" in first.upper():
            currency = "USDT"
        else:
            currency = "unknown"

    return {"amount": amount, "currency": currency, "raw_matches": matches}


def is_likely_bounty_issue(issue: Dict[str, Any]) -> Tuple[bool, str]:
    """Determine if an issue likely contains a bounty."""
    title = (issue.get("title") or "").lower()
    body = (issue.get("body") or "").lower()
    combined = f"{title}\n{body}"

    labels = [lbl["name"].lower() for lbl in issue.get("labels", [])]
    for label in labels:
        if any(w in label for w in ("bounty", "paid", "reward", "prize")):
            return True, f"label \"{label}\""

    if "pull_request" in issue:
        return False, "is a pull request, not an issue"

    for word in BOUNTY_INDICATOR_WORDS:
        if word.lower() in combined:
            return True, f"contains \"{word}\""

    for pattern in BOUNTY_CURRENCY_PATTERNS:
        if re.search(pattern, combined, re.IGNORECASE):
            return True, "amount pattern matched"

    return False, "no bounty indicators"


def filter_bounty_issues(issues: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Filter issues to those likely containing bounties."""
    result = []
    for issue in issues:
        is_bounty, reason = is_likely_bounty_issue(issue)
        if is_bounty:
            body = issue.get("body") or ""
            title = issue.get("title") or ""
            issue["bounty_info"] = extract_bounty_info(f"{title}\n{body}")
            issue["bounty_reason"] = reason
            result.append(issue)
            log.info("  OK #%d (%s) --- %s", issue["number"], str(issue.get("title", ""))[:60], reason)
        else:
            log.debug("  SKIP #%d --- %s", issue["number"], reason)
    log.info("After filtering: %d bounty issues", len(result))
    return result


def get_issue_detail(gh: GitHubClient, issue_url: str) -> Dict[str, Any]:
    """Get full issue details."""
    resp = gh.get(issue_url)
    resp.raise_for_status()
    return resp.json()


def get_repo_file_tree(
    gh: GitHubClient, owner: str, repo: str, branch: str = "main"
) -> Optional[List[Dict[str, Any]]]:
    """Get the repository root file tree (first level only)."""
    try:
        resp = gh.get(
            f"{GITHUB_API_BASE}/repos/{owner}/{repo}/git/trees/{branch}?recursive=0"
        )
        resp.raise_for_status()
        return resp.json().get("tree", [])
    except Exception as exc:
        log.warning("Failed to get file tree (%s/%s): %s", owner, repo, exc)
        return None


def get_file_content(
    gh: GitHubClient, owner: str, repo: str, path: str, ref: str = "main"
) -> Optional[str]:
    """Get the content of a single file from a repository."""
    try:
        resp = gh.get(
            f"{GITHUB_API_BASE}/repos/{owner}/{repo}/contents/{path}?ref={ref}"
        )
        resp.raise_for_status()
        data = resp.json()
        return base64.b64decode(data["content"]).decode("utf-8", errors="replace")
    except Exception as exc:
        log.debug("Failed to get file content (%s): %s", path, exc)
        return None


def extract_repo_info(issue: Dict[str, Any]) -> Tuple[str, str, int, str]:
    """Extract owner, repo, issue_number, repo_full_name from issue data."""
    url = issue.get("repository_url", "") or issue.get("url", "")
    parts = url.rstrip("/").split("/")
    owner = parts[-2] if len(parts) >= 2 else ""
    repo = parts[-1] if len(parts) >= 1 else ""
    number = issue.get("number", 0)
    full_name = f"{owner}/{repo}"
    return owner, repo, number, full_name


class CodexClient:
    """Encapsulates OpenAI API calls for code generation."""

    def __init__(self, api_key: str, model: str = "gpt-4o") -> None:
        self.client = OpenAI(api_key=api_key)
        self.model = model

    def analyze_issue(
        self,
        issue_title: str,
        issue_body: str,
        file_tree: Optional[List[Dict[str, Any]]] = None,
    ) -> str:
        """Analyze an issue and return a summary with fix suggestions."""
        tree_desc = ""
        if file_tree:
            tree_paths = [
                f["path"] for f in file_tree[:30] if f.get("type") != "tree"
            ]
            tree_desc = "\n".join(f"  - {p}" for p in tree_paths)

        prompt = f"""You are an expert software engineer. Analyze the following GitHub issue and provide:
1. A concise summary of the problem.
2. Root cause analysis.
3. A detailed fix plan.
4. Which files likely need changes.

## Issue Title
{issue_title}

## Issue Body
{issue_body}

## Repository Files (top-level)
{tree_desc or "(not available)"}

Respond in a structured format."""

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are an expert software engineer helping to fix GitHub issues. Be thorough and precise."},
                    {"role": "user", "content": prompt},
                ],
                temperature=0.3,
                max_tokens=1500,
            )
            return response.choices[0].message.content or ""
        except Exception as exc:
            log.error("OpenAI analysis failed: %s", exc)
            return f"[Analysis failed: {exc}]"

    def generate_fix(
        self,
        issue_title: str,
        issue_body: str,
        analysis: str,
        relevant_files: Optional[Dict[str, str]] = None,
    ) -> Dict[str, Any]:
        """Generate code fix based on issue and context."""
        files_section = ""
        if relevant_files:
            files_section = "## Current File Contents\n\n"
            for path, content in relevant_files.items():
                truncated = content[:4000]
                files_section += f"### {path}\n```\n{truncated}\n```\n\n"

        prompt = f"""You are an expert software engineer. Based on the issue and analysis below,
generate the exact code changes needed to fix the problem.

## Issue
Title: {issue_title}
Body: {issue_body[:3000]}

## Analysis
{analysis[:2000]}

{files_section}

## Instructions
Output a JSON object with this exact structure:
{{
  "description": "Brief summary of changes made",
  "files": [
    {{"path": "relative/path/to/file", "content": "full updated file content"}}
  ]
}}

Provide the COMPLETE updated file content for each modified file.
Only include files that actually need changes.
Ensure the JSON is valid."""

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are an expert software engineer. Output valid JSON only."},
                    {"role": "user", "content": prompt},
                ],
                temperature=0.2,
                max_tokens=4000,
                response_format={"type": "json_object"},
            )
            result_text = response.choices[0].message.content or "{}"
            result_text = re.sub(r"^```(?:json)?\s*", "", result_text.strip())
            result_text = re.sub(r"\s*```$", "", result_text.strip())
            return json.loads(result_text)
        except json.JSONDecodeError as exc:
            log.error("Failed to parse OpenAI JSON response: %s", exc)
            return {"description": "Failed to parse", "files": []}
        except Exception as exc:
            log.error("OpenAI fix generation failed: %s", exc)
            return {"description": f"Generation failed: {exc}", "files": []}


def check_existing_prs(
    gh: GitHubClient, owner: str, repo: str, issue_number: int, author_login: str
) -> bool:
    """Check if a PR from the same author already exists for this issue."""
    try:
        resp = gh.get(
            f"{GITHUB_API_BASE}/search/issues"
            f"?q=type:pr+repo:{owner}/{repo}+{issue_number}+state:open"
        )
        resp.raise_for_status()
        data = resp.json()
        for item in data.get("items", []):
            pr_user = item.get("user", {}).get("login", "")
            if pr_user == author_login:
                log.warning(
                    "Existing PR #%d by %s already references issue #%d",
                    item["number"], author_login, issue_number,
                )
                return True
    except Exception as exc:
        log.warning("Failed to check existing PRs: %s", exc)
    return False


def fork_repository(gh: GitHubClient, owner: str, repo: str) -> Optional[str]:
    """Fork a repository and return the fork full_name."""
    try:
        user = gh.user_login
        resp = gh.get(f"{GITHUB_API_BASE}/repos/{user}/{repo}")
        if resp.status_code == 200:
            log.info("Fork already exists: %s/%s", user, repo)
            return f"{user}/{repo}"
    except Exception:
        pass

    try:
        resp = gh.post(f"{GITHUB_API_BASE}/repos/{owner}/{repo}/forks", {})
        resp.raise_for_status()
        data = resp.json()
        forked = data["full_name"]
        log.info("Forked repository: %s", forked)
        time.sleep(3)
        return forked
    except Exception as exc:
        log.error("Failed to fork repository (%s/%s): %s", owner, repo, exc)
        return None


def get_default_branch(gh: GitHubClient, owner: str, repo: str) -> str:
    """Get the default branch of a repository."""
    try:
        resp = gh.get(f"{GITHUB_API_BASE}/repos/{owner}/{repo}")
        resp.raise_for_status()
        return resp.json().get("default_branch", "main")
    except Exception:
        return "main"


def get_latest_commit_sha(
    gh: GitHubClient, owner: str, repo: str, branch: str
) -> Optional[str]:
    """Get the latest commit SHA for a branch."""
    try:
        resp = gh.get(
            f"{GITHUB_API_BASE}/repos/{owner}/{repo}/git/refs/heads/{branch}"
        )
        resp.raise_for_status()
        return resp.json()["object"]["sha"]
    except Exception as exc:
        log.error("Failed to get branch SHA: %s", exc)
        return None


def create_branch(
    gh: GitHubClient, owner: str, repo: str, branch_name: str, base_sha: str
) -> bool:
    """Create a new branch in the fork repository."""
    try:
        resp = gh.post(
            f"{GITHUB_API_BASE}/repos/{owner}/{repo}/git/refs",
            {"ref": f"refs/heads/{branch_name}", "sha": base_sha},
        )
        if resp.status_code == 422:
            log.info("Branch %s already exists", branch_name)
            return True
        resp.raise_for_status()
        log.info("Created branch: %s", branch_name)
        return True
    except Exception as exc:
        log.error("Failed to create branch: %s", exc)
        return False


def create_blob(gh: GitHubClient, owner: str, repo: str, content: str) -> Optional[str]:
    """Create a Git blob and return its SHA."""
    try:
        resp = gh.post(
            f"{GITHUB_API_BASE}/repos/{owner}/{repo}/git/blobs",
            {"content": content, "encoding": "utf-8"},
        )
        resp.raise_for_status()
        return resp.json()["sha"]
    except Exception as exc:
        log.error("Failed to create blob: %s", exc)
        return None


def create_tree(
    gh: GitHubClient,
    owner: str,
    repo: str,
    base_tree_sha: str,
    files: List[Dict[str, str]],
) -> Optional[str]:
    """Create a Git tree and return its SHA."""
    tree_items = []
    for f in files:
        blob_sha = create_blob(gh, owner, repo, f["content"])
        if not blob_sha:
            return None
        tree_items.append({
            "path": f["path"],
            "mode": "100644",
            "type": "blob",
            "sha": blob_sha,
        })

    try:
        resp = gh.post(
            f"{GITHUB_API_BASE}/repos/{owner}/{repo}/git/trees",
            {"base_tree": base_tree_sha, "tree": tree_items},
        )
        resp.raise_for_status()
        return resp.json()["sha"]
    except Exception as exc:
        log.error("Failed to create tree: %s", exc)
        return None


def create_commit(
    gh: GitHubClient,
    owner: str,
    repo: str,
    message: str,
    tree_sha: str,
    parent_sha: str,
) -> Optional[str]:
    """Create a Git commit and return its SHA."""
    try:
        resp = gh.post(
            f"{GITHUB_API_BASE}/repos/{owner}/{repo}/git/commits",
            {"message": message, "tree": tree_sha, "parents": [parent_sha]},
        )
        resp.raise_for_status()
        return resp.json()["sha"]
    except Exception as exc:
        log.error("Failed to create commit: %s", exc)
        return None


def update_branch_ref(
    gh: GitHubClient, owner: str, repo: str, branch: str, sha: str
) -> bool:
    """Update a branch reference to point to a new commit."""
    try:
        resp = gh.patch(
            f"{GITHUB_API_BASE}/repos/{owner}/{repo}/git/refs/heads/{branch}",
            {"sha": sha, "force": False},
        )
        resp.raise_for_status()
        log.info("Branch %s updated to %s", branch, sha[:8])
        return True
    except Exception as exc:
        log.error("Failed to update branch ref: %s", exc)
        return False


def create_pull_request(
    gh: GitHubClient,
    owner: str,
    repo: str,
    head: str,
    base: str,
    title: str,
    body: str,
) -> Optional[Dict[str, Any]]:
    """Create a Pull Request."""
    try:
        resp = gh.post(
            f"{GITHUB_API_BASE}/repos/{owner}/{repo}/pulls",
            {"title": title, "body": body, "head": head, "base": base},
        )
        resp.raise_for_status()
        data = resp.json()
        log.info("Created PR: %s", data.get("html_url", "N/A"))
        return data
    except Exception as exc:
        log.error("Failed to create PR: %s", exc)
        return None


def submit_fix_pr(
    gh: GitHubClient,
    owner: str,
    repo: str,
    issue: Dict[str, Any],
    fix_result: Dict[str, Any],
    dry_run: bool = False,
) -> bool:
    """Complete PR submission flow: fork, branch, commit, create PR."""
    issue_number = issue["number"]
    issue_title = issue["title"]
    repo_full = f"{owner}/{repo}"
    user = gh.user_login

    if check_existing_prs(gh, owner, repo, issue_number, user):
        log.info("Skipping issue #%d, PR already exists from %s", issue_number, user)
        return False

    if dry_run:
        log.info("[DRY-RUN] Would create PR for %s issue #%d", repo_full, issue_number)
        return True

    forked = fork_repository(gh, owner, repo)
    if not forked:
        return False

    fork_owner, fork_repo = forked.split("/")
    default_branch = get_default_branch(gh, owner, repo)
    log.info("Target default branch: %s", default_branch)

    base_sha = get_latest_commit_sha(gh, fork_owner, fork_repo, default_branch)
    if not base_sha:
        log.error("Could not get latest commit on fork")
        return False

    branch_name = f"fix/issue-{issue_number}-bounty"
    if not create_branch(gh, fork_owner, fork_repo, branch_name, base_sha):
        return False

    files = fix_result.get("files", [])
    if not files:
        log.warning("No files generated for fix")
        return False

    tree_sha = create_tree(gh, fork_owner, fork_repo, base_sha, files)
    if not tree_sha:
        return False

    commit_message = f"Fix #{issue_number}: {issue_title[:70]}"
    commit_sha = create_commit(gh, fork_owner, fork_repo, commit_message, tree_sha, base_sha)
    if not commit_sha:
        return False

    if not update_branch_ref(gh, fork_owner, fork_repo, branch_name, commit_sha):
        return False

    pr_body = PR_BODY_TEMPLATE.format(
        issue_number=issue_number,
        issue_title=issue_title,
        changes_summary=fix_result.get("description", "See commit for details."),
    )
    pr_title = f"Fix #{issue_number}: {issue_title[:60]}"

    pr = create_pull_request(
        gh, owner, repo,
        head=f"{fork_owner}:{branch_name}",
        base=default_branch,
        title=pr_title,
        body=pr_body,
    )

    return pr is not None


def process_single_issue(
    gh: GitHubClient,
    codex: CodexClient,
    issue: Dict[str, Any],
    dry_run: bool = False,
) -> bool:
    """Process a single bounty issue: analyze, generate fix, submit PR."""
    owner, repo, number, full_name = extract_repo_info(issue)
    log.info("=" * 60)
    log.info("Processing issue #%d: %s", number, issue.get("title", "N/A"))
    log.info("Repository: %s", full_name)

    bounty = issue.get("bounty_info", {})
    if bounty.get("amount"):
        log.info("Bounty: %s %s", bounty["amount"], bounty.get("currency", "?"))

    issue_url = issue.get("url", "")
    detail = get_issue_detail(gh, issue_url) if issue_url else issue
    issue_body = detail.get("body") or ""
    issue_title = detail.get("title") or ""

    file_tree = get_repo_file_tree(gh, owner, repo)

    log.info("Analyzing issue...")
    analysis = codex.analyze_issue(issue_title, issue_body, file_tree)
    log.info("Analysis:\n%s", analysis[:500])

    relevant_files: Dict[str, str] = {}
    if file_tree:
        source_exts = {".py", ".js", ".ts", ".go", ".rs", ".java", ".rb", ".c", ".cpp", ".h"}
        for f in file_tree[:15]:
            path = f.get("path", "")
            if any(path.endswith(ext) for ext in source_exts) and f.get("type") == "blob":
                content = get_file_content(gh, owner, repo, path)
                if content and len(content) < 5000:
                    relevant_files[path] = content

    log.info("Generating fix code...")
    time.sleep(random.uniform(0.5, 1.5))
    fix_result = codex.generate_fix(issue_title, issue_body, analysis, relevant_files)

    if not fix_result.get("files"):
        log.warning("No fix code generated")
        return False

    log.info("Generated %d file changes:", len(fix_result["files"]))
    for f in fix_result["files"]:
        log.info("  - %s (%d chars)", f["path"], len(f.get("content", "")))

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    output_file = os.path.join(
        OUTPUT_DIR, f"issue_{number}_{owner}_{repo}_{timestamp}.json"
    )
    output_data = {
        "issue": {
            "number": number,
            "title": issue_title,
            "url": detail.get("html_url", ""),
            "repository": full_name,
        },
        "bounty_info": bounty,
        "analysis": analysis,
        "fix": fix_result,
        "timestamp": timestamp,
        "dry_run": dry_run,
    }
    with open(output_file, "w", encoding="utf-8") as fp:
        json.dump(output_data, fp, ensure_ascii=False, indent=2)
    log.info("Analysis saved to: %s", output_file)

    success = submit_fix_pr(gh, owner, repo, issue, fix_result, dry_run=dry_run)

    delay = random.uniform(2.0, 5.0)
    log.info("Waiting %.1f seconds before next...", delay)
    time.sleep(delay)

    return success


def main() -> None:
    parser = argparse.ArgumentParser(
        description="GitHub Bounty Hunter - Auto-find bounty issues and submit fix PRs",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Examples:
  python github_bounty_hunter.py                  # Full run
  python github_bounty_hunter.py --dry-run        # Analyze only, no PR
  python github_bounty_hunter.py --limit 3        # Max 3 issues
  python github_bounty_hunter.py --issue https://github.com/owner/repo/issues/123
  python github_bounty_hunter.py --model gpt-4o   # Specify model

Required env vars:
  GITHUB_TOKEN       GitHub Personal Access Token
  OPENAI_API_KEY     OpenAI API Key
""",
    )
    parser.add_argument("--dry-run", action="store_true", help="Analyze and generate only, do not create branches or PRs")
    parser.add_argument("--limit", type=int, default=5, help="Max issues to process (default: 5)")
    parser.add_argument("--issue", type=str, default=None, help="Single issue URL to process")
    parser.add_argument("--model", type=str, default="gpt-4o", help="OpenAI model name (default: gpt-4o)")
    parser.add_argument("--query", type=str, default=None, help="Extra GitHub search query to append")
    parser.add_argument("--min-bounty", type=float, default=0, help="Minimum bounty amount in USD (default: 0)")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose debug logging")

    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    github_token = os.environ.get("GITHUB_TOKEN", "")
    openai_api_key = os.environ.get("OPENAI_API_KEY", "")

    if not github_token:
        log.error("GITHUB_TOKEN environment variable not set")
        sys.exit(1)
    if not openai_api_key:
        log.error("OPENAI_API_KEY environment variable not set")
        sys.exit(1)

    log.info("GitHub Bounty Hunter starting")
    log.info("Mode: %s", "DRY-RUN (no PRs will be created)" if args.dry_run else "LIVE")
    log.info("Model: %s", args.model)
    log.info("Processing limit: %d", args.limit)

    gh = GitHubClient(github_token)
    codex = CodexClient(openai_api_key, model=args.model)

    try:
        user = gh.user_login
        log.info("Authenticated as GitHub user: %s", user)
    except Exception as exc:
        log.error("GitHub authentication failed: %s", exc)
        sys.exit(1)

    if args.issue:
        log.info("Single-issue mode: %s", args.issue)
        parsed = urlparse(args.issue)
        path_parts = parsed.path.strip("/").split("/")
        if len(path_parts) < 4 or path_parts[2] != "issues":
            log.error("Invalid issue URL, expected format: https://github.com/owner/repo/issues/123")
            sys.exit(1)
        owner, repo, _, number_str = path_parts[-4], path_parts[-3], path_parts[-2], path_parts[-1]
        try:
            issue_number = int(number_str)
        except ValueError:
            log.error("Cannot parse issue number: %s", number_str)
            sys.exit(1)

        resp = gh.get(f"{GITHUB_API_BASE}/repos/{owner}/{repo}/issues/{issue_number}")
        resp.raise_for_status()
        issue = resp.json()
        issue["bounty_info"] = extract_bounty_info(
            f"{issue.get('title', '')}\n{issue.get('body', '')}"
        )
        issues = [issue]
    else:
        log.info("Searching for bounty issues...")
        candidates = search_bounty_issues(gh, limit=args.limit * 3, extra_query=args.query)
        issues = filter_bounty_issues(candidates)

        if args.min_bounty > 0:
            filtered = []
            for iss in issues:
                bi = iss.get("bounty_info", {})
                amt = bi.get("amount")
                if amt:
                    try:
                        if float(amt) >= args.min_bounty:
                            filtered.append(iss)
                    except ValueError:
                        filtered.append(iss)
                else:
                    filtered.append(iss)
            issues = filtered
            log.info("After min-bounty filter: %d issues", len(issues))

        issues = issues[: args.limit]

    if not issues:
        log.info("No matching issues found")
        sys.exit(0)

    log.info("Will process %d issues", len(issues))

    success_count = 0
    for idx, issue in enumerate(issues, 1):
        log.info("\n[%d/%d]", idx, len(issues))
        try:
            if process_single_issue(gh, codex, issue, dry_run=args.dry_run):
                success_count += 1
        except Exception as exc:
            log.error("Error processing issue: %s", exc, exc_info=args.verbose)
            continue

    log.info("\n" + "=" * 60)
    log.info("Done! Successfully processed %d/%d issues", success_count, len(issues))
    log.info("Output directory: %s/", OUTPUT_DIR)

    if args.dry_run:
        log.info("\n*** DRY-RUN mode: No branches or PRs were actually created.")
        log.info("    Review outputs in %s/ then re-run with --issue to submit.", OUTPUT_DIR)


if __name__ == "__main__":
    main()
