#!/usr/bin/env python3
"""
GitHub Bounty Hunter --- 自动搜寻 GitHub 上有赏金 Issue 并提交修复 PR 的自动化工具。

用法:
    python github_bounty_hunter.py                  # 完整运行
    python github_bounty_hunter.py --dry-run        # 仅搜索分析生成, 不提交 PR
    python github_bounty_hunter.py --limit 5         # 最多处理 5 个 issue
    python github_bounty_hunter.py --issue <url>     # 单个 issue

环境变量:
    GITHUB_TOKEN      GitHub Personal Access Token (必须)
    OPENAI_API_KEY    OpenAI API Key (必须)

风险警告:
    自动化提交 PR 可能被仓库维护者视为垃圾信息。强烈建议初期使用 --dry-run
    模式, 人工审核生成的修复代码后再手动提交。请在遵守 GitHub 服务条款和
    各仓库行为准则的前提下使用本工具。
"""

from __future__ import annotations

import argparse
import base64
import json
import logging
import os
import random
import re
import sys
import textwrap
import time
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple
from urllib.parse import urlparse

import requests
from openai import OpenAI

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger("bounty_hunter")

GITHUB_API_BASE = "https://api.github.com"
USER_AGENT = "GitHub-Bounty-Hunter/1.0"

BOUNTY_SEARCH_QUERIES: List[str] = [
    "label:bounty+state:open+is:issue",
    "bounty+state:open+is:issue",
    "label:\"good first issue\"+state:open+is:issue+label:\"help wanted\"",
    "label:\"help wanted\"+state:open+is:issue+bounty",
    "label:paid+state:open+is:issue",
    "label:reward+state:open+is:issue",
    "\"$\"+state:open+is:issue+label:\"help wanted\"",
]

BOUNTY_CURRENCY_PATTERNS: List[str] = [
    r"\$\s*\d[\d,]*(?:\.\d{1,2})?",
    r"\d[\d,]*(?:\.\d{1,2})?\s*USD",
    r"\d[\d,]*(?:\.\d{1,2})?\s*ETH",
    r"\d[\d,]*(?:\.\d{1,2})?\s*USDC",
    r"\d[\d,]*(?:\.\d{1,2})?\s*USDT",
    r"(?:bounty|reward)\s*:?\s*\$?\s*\d[\d,]*(?:\.\d{1,2})?",
]

BOUNTY_INDICATOR_WORDS: List[str] = [
    "bounty", "reward", "paid", "payment", "prize", "compensation",
    "💰", "💵", "💲", "🪙", "funded", "pays", "payout",
]

PR_BODY_TEMPLATE = """## Summary

This PR resolves **#{issue_number}**: {issue_title}

## Changes

{changes_summary}

## Bounty Note

According to the bounty mentioned in the original issue, this fix should
be eligible for the associated reward. If you need payment details or
further information, please reach out via the method described in the issue.

---
*This PR was auto-generated by GitHub Bounty Hunter.
Please review carefully --- AI-generated code may contain errors.*
"""

OUTPUT_DIR = "outputs"


class GitHubClient:
    """Encapsulates GitHub REST API v3 operations."""

    def __init__(self, token: str) -> None:
        self.token = token
        self.session = requests.Session()
        self.session.headers.update({
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "User-Agent": USER_AGENT,
            "X-GitHub-Api-Version": "2022-11-28",
        })
        self._rate_limit_remaining = 5000
        self._rate_limit_reset = 0
        self._user_login: Optional[str] = None

    def _update_rate_limit(self, response: requests.Response) -> None:
        self._rate_limit_remaining = int(
            response.headers.get("X-RateLimit-Remaining", self._rate_limit_remaining)
        )
        self._rate_limit_reset = int(
            response.headers.get("X-RateLimit-Reset", self._rate_limit_reset)
        )

    def _wait_if_needed(self) -> None:
        if self._rate_limit_remaining < 10:
            now = int(time.time())
            wait = max(self._rate_limit_reset - now + 2, 1)
            log.warning("Rate limit nearly exhausted, waiting %d seconds...", wait)
            time.sleep(wait)

    def _request(
        self,
        method: str,
        url: str,
        *,
        json_body: Optional[Dict[str, Any]] = None,
        max_retries: int = 3,
    ) -> requests.Response:
        self._wait_if_needed()
        last_exc: Optional[Exception] = None

        for attempt in range(1, max_retries + 1):
            try:
                resp = self.session.request(method, url, json=json_body, timeout=30)
                self._update_rate_limit(resp)

                if resp.status_code == 403 and "rate limit" in resp.text.lower():
                    reset_time = int(resp.headers.get("X-RateLimit-Reset", time.time() + 60))
                    wait = max(reset_time - int(time.time()) + 2, 5)
                    log.warning("Secondary rate limit triggered, waiting %d seconds...", wait)
                    time.sleep(wait)
                    continue

                if resp.status_code >= 500:
                    log.warning("Server error %d, retry %d/%d", resp.status_code, attempt, max_retries)
                    time.sleep(2 ** attempt)
                    continue

                return resp

            except requests.RequestException as exc:
                last_exc = exc
                log.warning("Request failed (attempt %d/%d): %s", attempt, max_retries, exc)
                if attempt < max_retries:
                    time.sleep(2 ** attempt)

        raise last_exc  # type: ignore[misc]

    def get(self, url: str, **kwargs: Any) -> requests.Response:
        return self._request("GET", url, **kwargs)

    def post(self, url: str, **kwargs: Any) -> requests.Response:
        return self._request("POST", url, **kwargs)

    def patch(self, url: str, **kwargs: Any) -> requests.Response:
        return self._request("PATCH", url, **kwargs)

    def put(self, url: str, **kwargs: Any) -> requests.Response:
        return self._request("PUT", url, **kwargs)

    def delete(self, url: str, **kwargs: Any) -> requests.Response:
        return self._request("DELETE", url, **kwargs)

    @property
    def user_login(self) -> str:
        if self._user_login is None:
            resp = self.get(f"{GITHUB_API_BASE}/user")
            resp.raise_for_status()
            self._user_login = resp.json()["login"]
        return self._user_login


class CodexClient:
    """Encapsulates OpenAI API operations for code generation."""

    def __init__(self, api_key: str, model: str = "gpt-4o") -> None:
        self.client = OpenAI(api_key=api_key)
        self.model = model

    def analyze_issue(
        self, title: str, body: str, repo_full_name: str
    ) -> Dict[str, Any]:
        """Analyze a GitHub issue and return structured analysis."""
        prompt = f"""You are an expert software developer. Analyze the following GitHub issue
from repository {repo_full_name} and provide a structured response.

Issue Title: {title}

Issue Body:
{body[:6000]}

Provide your analysis in the following JSON structure:
{{
    "summary": "Brief summary of the issue",
    "bounty_confirmed": true/false,
    "estimated_bounty": "amount if confirmed, otherwise null",
    "difficulty": "easy/medium/hard",
    "involved_files": ["list of likely files to modify"],
    "root_cause": "Root cause analysis",
    "suggested_fix": "Detailed description of the fix approach"
}}
"""
        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": "You are an expert software developer. Always respond in valid JSON."},
                {"role": "user", "content": prompt},
            ],
            temperature=0.3,
            max_tokens=2000,
        )
        content = response.choices[0].message.content or "{}"
        # Try to extract JSON from the response
        try:
            return json.loads(content)
        except json.JSONDecodeError:
            # Try to find JSON in markdown code blocks
            match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", content, re.DOTALL)
            if match:
                try:
                    return json.loads(match.group(1))
                except json.JSONDecodeError:
                    pass
            log.warning("Failed to parse analysis JSON, returning raw content")
            return {"raw_analysis": content}

    def generate_fix(
        self,
        issue_title: str,
        issue_body: str,
        analysis: Dict[str, Any],
        repo_full_name: str,
    ) -> Dict[str, Any]:
        """Generate code fix based on issue analysis."""
        prompt = f"""You are an expert software developer. Generate a code fix for the following
GitHub issue from repository {repo_full_name}.

Issue Title: {issue_title}

Issue Body:
{issue_body[:4000]}

Analysis:
{json.dumps(analysis, indent=2)}

Provide your fix in the following JSON structure:
{{
    "files_to_modify": [
        {{
            "path": "relative/path/to/file",
            "description": "What needs to change in this file",
            "patch": "The actual code changes to make"
        }}
    ],
    "files_to_create": [
        {{
            "path": "relative/path/to/new/file",
            "content": "Full file content"
        }}
    ],
    "commit_message": "Concise commit message",
    "changes_summary": "Summary of changes made"
}}
"""
        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": "You are an expert software developer. Always respond in valid JSON."},
                {"role": "user", "content": prompt},
            ],
            temperature=0.3,
            max_tokens=4000,
        )
        content = response.choices[0].message.content or "{}"
        try:
            return json.loads(content)
        except json.JSONDecodeError:
            match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", content, re.DOTALL)
            if match:
                try:
                    return json.loads(match.group(1))
                except json.JSONDecodeError:
                    pass
            log.warning("Failed to parse fix JSON, returning raw content")
            return {"raw_fix": content}


def search_bounty_issues(
    gh: GitHubClient,
    limit: int = 15,
    extra_query: Optional[str] = None,
) -> List[Dict[str, Any]]:
    """Search GitHub for issues that may have bounties."""
    all_issues: List[Dict[str, Any]] = []
    seen: set = set()

    for query in BOUNTY_SEARCH_QUERIES:
        if len(all_issues) >= limit * 2:
            break

        full_query = f"{query}+archived:false+is:issue"
        if extra_query:
            full_query += f"+{extra_query}"

        url = f"{GITHUB_API_BASE}/search/issues?q={full_query}&sort=created&order=desc&per_page={min(limit, 10)}"

        try:
            resp = gh.get(url)
            resp.raise_for_status()
            data = resp.json()

            for item in data.get("items", []):
                issue_id = item["id"]
                if issue_id in seen:
                    continue
                seen.add(issue_id)

                # Skip pull requests (they appear in issue search too)
                if "pull_request" in item:
                    continue

                all_issues.append(item)

                if len(all_issues) >= limit * 2:
                    break

        except Exception as exc:
            log.error("Search query '%s' failed: %s", query, exc)
            continue

        delay = random.uniform(1.0, 3.0)
        time.sleep(delay)

    log.info("Found %d candidate issues", len(all_issues))
    return all_issues


def extract_bounty_info(text: str) -> Dict[str, Any]:
    """Extract bounty information from issue text."""
    if not text:
        return {"has_bounty": False, "amount": None, "currency": None, "mentions": []}

    text_lower = text.lower()
    mentions = [w for w in BOUNTY_INDICATOR_WORDS if w in text_lower or w in text]

    amounts = []
    for pattern in BOUNTY_CURRENCY_PATTERNS:
        matches = re.findall(pattern, text, re.IGNORECASE)
        for m in matches:
            # Extract numeric value
            num_match = re.search(r"\d[\d,]*", m)
            if num_match:
                num_str = num_match.group().replace(",", "")
                try:
                    amount = float(num_str)
                    currency = "USD"
                    if "ETH" in m.upper():
                        currency = "ETH"
                    elif "USDC" in m.upper():
                        currency = "USDC"
                    elif "USDT" in m.upper():
                        currency = "USDT"
                    elif "$" in m:
                        currency = "USD"
                    amounts.append((amount, currency, m.strip()))
                except ValueError:
                    pass

    has_bounty = bool(mentions) or bool(amounts)
    max_amount = None
    max_currency = None
    if amounts:
        amounts.sort(key=lambda x: x[0], reverse=True)
        max_amount, max_currency, _ = amounts[0]

    return {
        "has_bounty": has_bounty,
        "amount": max_amount,
        "currency": max_currency,
        "mentions": mentions,
        "all_amounts": amounts,
    }


def filter_bounty_issues(issues: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Filter issues to those likely having bounties."""
    filtered = []

    for issue in issues:
        title = issue.get("title", "")
        body = issue.get("body", "") or ""
        labels = [lbl.get("name", "").lower() for lbl in issue.get("labels", [])]

        combined_text = f"{title}\n{body}"
        bounty_info = extract_bounty_info(combined_text)

        # Check labels for bounty indicators
        label_has_bounty = any(
            any(w in label for w in ["bounty", "reward", "paid", "payment", "prize"])
            for label in labels
        )

        if bounty_info["has_bounty"] or label_has_bounty:
            issue["bounty_info"] = bounty_info
            filtered.append(issue)

    log.info("Filtered to %d issues with bounty indicators", len(filtered))
    return filtered


def check_duplicate_pr(
    gh: GitHubClient, owner: str, repo: str, issue_number: int
) -> bool:
    """Check if a PR already exists for the given issue."""
    try:
        url = f"{GITHUB_API_BASE}/search/issues?q=is:pr+repo:{owner}/{repo}+Fixes #{issue_number}"
        resp = gh.get(url)
        resp.raise_for_status()
        data = resp.json()
        return data.get("total_count", 0) > 0
    except Exception as exc:
        log.warning("Failed to check duplicate PRs: %s", exc)
        return False


def fork_repository(gh: GitHubClient, owner: str, repo: str) -> str:
    """Fork the repository and return the fork's full name."""
    # Check if already forked
    user = gh.user_login
    try:
        resp = gh.get(f"{GITHUB_API_BASE}/repos/{user}/{repo}")
        if resp.status_code == 200:
            log.info("Fork already exists: %s/%s", user, repo)
            return f"{user}/{repo}"
    except Exception:
        pass

    log.info("Forking %s/%s...", owner, repo)
    resp = gh.post(f"{GITHUB_API_BASE}/repos/{owner}/{repo}/forks")
    resp.raise_for_status()

    # Wait for fork to be ready
    for _ in range(30):
        try:
            fork_resp = gh.get(f"{GITHUB_API_BASE}/repos/{user}/{repo}")
            if fork_resp.status_code == 200:
                log.info("Fork ready: %s/%s", user, repo)
                return f"{user}/{repo}"
        except Exception:
            pass
        time.sleep(2)

    raise RuntimeError(f"Fork of {owner}/{repo} did not become ready in time")


def create_fix_branch(
    gh: GitHubClient,
    fork_full_name: str,
    issue_number: int,
    base_branch: str = "main",
) -> str:
    """Create a new branch for the fix in the forked repository."""
    branch_name = f"bounty-fix-issue-{issue_number}-{int(time.time())}"

    # Get the base branch SHA
    owner, repo = fork_full_name.split("/")
    resp = gh.get(f"{GITHUB_API_BASE}/repos/{owner}/{repo}/git/refs/heads/{base_branch}")
    resp.raise_for_status()
    base_sha = resp.json()["object"]["sha"]

    # Create new branch
    gh.post(
        f"{GITHUB_API_BASE}/repos/{owner}/{repo}/git/refs",
        json_body={"ref": f"refs/heads/{branch_name}", "sha": base_sha},
    )

    log.info("Created branch: %s", branch_name)
    return branch_name


def apply_fix_to_branch(
    gh: GitHubClient,
    fork_full_name: str,
    branch_name: str,
    fix_result: Dict[str, Any],
) -> List[str]:
    """Apply code changes to the branch. Returns list of modified file paths."""
    owner, repo = fork_full_name.split("/")
    modified_files = []

    for file_info in fix_result.get("files_to_modify", []):
        path = file_info["path"]
        patch_content = file_info.get("patch", "")

        if not patch_content:
            continue

        # Get current file content
        try:
            resp = gh.get(
                f"{GITHUB_API_BASE}/repos/{owner}/{repo}/contents/{path}",
                json_body={"ref": branch_name},
            )
            resp.raise_for_status()
            current_file = resp.json()
            current_sha = current_file["sha"]
            current_content = base64.b64decode(current_file["content"]).decode("utf-8")
        except Exception:
            log.warning("Could not read %s, skipping", path)
            continue

        # Simple patch application (replace the entire file with AI-generated content)
        # In production, you'd want proper diff application
        new_content = patch_content if patch_content else current_content

        gh.put(
            f"{GITHUB_API_BASE}/repos/{owner}/{repo}/contents/{path}",
            json_body={
                "message": f"Fix #{fix_result.get('issue_number', '?')}: {file_info.get('description', 'Update')}",
                "content": base64.b64encode(new_content.encode("utf-8")).decode("utf-8"),
                "sha": current_sha,
                "branch": branch_name,
            },
        )
        modified_files.append(path)
        log.info("Updated: %s", path)

    for file_info in fix_result.get("files_to_create", []):
        path = file_info["path"]
        content = file_info.get("content", "")

        if not content:
            continue

        gh.put(
            f"{GITHUB_API_BASE}/repos/{owner}/{repo}/contents/{path}",
            json_body={
                "message": f"Add {path}",
                "content": base64.b64encode(content.encode("utf-8")).decode("utf-8"),
                "branch": branch_name,
            },
        )
        modified_files.append(path)
        log.info("Created: %s", path)

    return modified_files


def create_fix_pr(
    gh: GitHubClient,
    fork_full_name: str,
    upstream_owner: str,
    upstream_repo: str,
    branch_name: str,
    issue: Dict[str, Any],
    fix_result: Dict[str, Any],
) -> Optional[Dict[str, Any]]:
    """Create a Pull Request from the fork branch to upstream."""
    fork_owner, _ = fork_full_name.split("/")
    issue_number = issue["number"]
    issue_title = issue["title"]

    title = f"Fix #{issue_number}: {issue_title[:80]}"
    body = PR_BODY_TEMPLATE.format(
        issue_number=issue_number,
        issue_title=issue_title,
        changes_summary=fix_result.get("changes_summary", "See commit details."),
    )

    resp = gh.post(
        f"{GITHUB_API_BASE}/repos/{upstream_owner}/{upstream_repo}/pulls",
        json_body={
            "title": title,
            "body": body,
            "head": f"{fork_owner}:{branch_name}",
            "base": "main",
        },
    )
    resp.raise_for_status()
    pr_data = resp.json()
    log.info("PR created: %s", pr_data.get("html_url", ""))
    return pr_data


def save_output(
    issue: Dict[str, Any],
    analysis: Dict[str, Any],
    fix_result: Dict[str, Any],
    dry_run: bool,
) -> str:
    """Save analysis and fix output to disk."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    full_name = issue.get("repository_url", "").split("/repos/")[-1] if issue.get("repository_url") else "unknown"
    issue_number = issue.get("number", "unknown")
    filename = f"issue_{full_name.replace('/', '_')}_{issue_number}_{timestamp}.json"
    output_file = os.path.join(OUTPUT_DIR, filename)

    output_data = {
        "issue": {
            "number": issue_number,
            "title": issue.get("title", ""),
            "url": issue.get("html_url", ""),
            "repository": full_name,
        },
        "bounty_info": issue.get("bounty_info", {}),
        "analysis": analysis,
        "fix": fix_result,
        "timestamp": timestamp,
        "dry_run": dry_run,
    }

    with open(output_file, "w", encoding="utf-8") as fp:
        json.dump(output_data, fp, ensure_ascii=False, indent=2)
    log.info("Analysis saved to: %s", output_file)

    return output_file


def submit_fix_pr(
    gh: GitHubClient,
    owner: str,
    repo: str,
    issue: Dict[str, Any],
    fix_result: Dict[str, Any],
    dry_run: bool = False,
) -> bool:
    """Submit a fix PR for an issue. Returns True if successful."""
    issue_number = issue["number"]

    if check_duplicate_pr(gh, owner, repo, issue_number):
        log.info("PR already exists for issue #%d, skipping", issue_number)
        return False

    if dry_run:
        log.info("[DRY-RUN] Would create PR for %s/%s#%d", owner, repo, issue_number)
        log.info("[DRY-RUN] Changes summary: %s", fix_result.get("changes_summary", "N/A"))
        return True

    try:
        fork_full_name = fork_repository(gh, owner, repo)
        branch_name = create_fix_branch(gh, fork_full_name, issue_number)
        modified_files = apply_fix_to_branch(gh, fork_full_name, branch_name, fix_result)

        if not modified_files:
            log.warning("No files were modified, skipping PR creation")
            return False

        pr_data = create_fix_pr(
            gh, fork_full_name, owner, repo, branch_name, issue, fix_result
        )
        return pr_data is not None

    except Exception as exc:
        log.error("Failed to submit PR for %s/%s#%d: %s", owner, repo, issue_number, exc)
        return False


def process_single_issue(
    gh: GitHubClient,
    codex: CodexClient,
    issue: Dict[str, Any],
    dry_run: bool = False,
) -> bool:
    """Process a single issue: analyze, generate fix, and optionally submit PR."""
    issue_number = issue["number"]
    issue_title = issue.get("title", "No title")
    issue_body = issue.get("body", "") or ""
    repo_url = issue.get("repository_url", "")
    full_name = repo_url.split("/repos/")[-1] if repo_url else "unknown/unknown"
    owner, repo = full_name.split("/") if "/" in full_name else ("unknown", "unknown")

    bounty = issue.get("bounty_info", extract_bounty_info(f"{issue_title}\n{issue_body}"))
    if bounty.get("amount"):
        log.info(
            "Issue #%d: %s (bounty: %s %s)",
            issue_number, issue_title, bounty["amount"], bounty.get("currency", "USD"),
        )
    else:
        log.info("Issue #%d: %s", issue_number, issue_title)

    # Step 1: Analyze
    log.info("Analyzing issue #%d with OpenAI...", issue_number)
    analysis = codex.analyze_issue(issue_title, issue_body, full_name)
    log.info("Analysis complete: difficulty=%s, confirmed=%s",
             analysis.get("difficulty", "unknown"), analysis.get("bounty_confirmed", False))

    # Step 2: Generate fix
    log.info("Generating fix for issue #%d...", issue_number)
    fix_result = codex.generate_fix(issue_title, issue_body, analysis, full_name)
    fix_result["issue_number"] = issue_number
    fix_result["issue_title"] = issue_title

    # Step 3: Save output
    output_file = save_output(issue, analysis, fix_result, dry_run)

    # Build output data for saving
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    output_data = {
        "issue": {
            "number": issue_number,
            "title": issue_title,
            "url": issue.get("html_url", ""),
            "repository": full_name,
        },
        "bounty_info": bounty,
        "analysis": analysis,
        "fix": fix_result,
        "timestamp": timestamp,
        "dry_run": dry_run,
    }
    with open(output_file, "w", encoding="utf-8") as fp:
        json.dump(output_data, fp, ensure_ascii=False, indent=2)
    log.info("Analysis saved to: %s", output_file)

    success = submit_fix_pr(gh, owner, repo, issue, fix_result, dry_run=dry_run)

    delay = random.uniform(2.0, 5.0)
    log.info("Waiting %.1f seconds before next...", delay)
    time.sleep(delay)

    return success


def main() -> None:
    parser = argparse.ArgumentParser(
        description="GitHub Bounty Hunter - Auto-find bounty issues and submit fix PRs",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Examples:
  python github_bounty_hunter.py                  # Full run
  python github_bounty_hunter.py --dry-run        # Analyze only, no PR
  python github_bounty_hunter.py --limit 3        # Max 3 issues
  python github_bounty_hunter.py --issue https://github.com/owner/repo/issues/123
  python github_bounty_hunter.py --model gpt-4o   # Specify model

Required env vars:
  GITHUB_TOKEN       GitHub Personal Access Token
  OPENAI_API_KEY     OpenAI API Key
""",
    )
    parser.add_argument("--dry-run", action="store_true", help="Analyze and generate only, do not create branches or PRs")
    parser.add_argument("--limit", type=int, default=5, help="Max issues to process (default: 5)")
    parser.add_argument("--issue", type=str, default=None, help="Single issue URL to process")
    parser.add_argument("--model", type=str, default="gpt-4o", help="OpenAI model name (default: gpt-4o)")
    parser.add_argument("--query", type=str, default=None, help="Extra GitHub search query to append")
    parser.add_argument("--min-bounty", type=float, default=0, help="Minimum bounty amount in USD (default: 0)")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose debug logging")

    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    github_token = os.environ.get("GITHUB_TOKEN", "")
    openai_api_key = os.environ.get("OPENAI_API_KEY", "")

    if not github_token:
        log.error("GITHUB_TOKEN environment variable not set")
        sys.exit(1)
    if not openai_api_key:
        log.error("OPENAI_API_KEY environment variable not set")
        sys.exit(1)

    log.info("GitHub Bounty Hunter starting")
    log.info("Mode: %s", "DRY-RUN (no PRs will be created)" if args.dry_run else "LIVE")
    log.info("Model: %s", args.model)
    log.info("Processing limit: %d", args.limit)

    gh = GitHubClient(github_token)
    codex = CodexClient(openai_api_key, model=args.model)

    try:
        user = gh.user_login
        log.info("Authenticated as GitHub user: %s", user)
    except Exception as exc:
        log.error("GitHub authentication failed: %s", exc)
        sys.exit(1)

    if args.issue:
        log.info("Single-issue mode: %s", args.issue)
        parsed = urlparse(args.issue)
        path_parts = parsed.path.strip("/").split("/")
        if len(path_parts) < 4 or path_parts[2] != "issues":
            log.error("Invalid issue URL, expected format: https://github.com/owner/repo/issues/123")
            sys.exit(1)
        owner, repo, _, number_str = path_parts[-4], path_parts[-3], path_parts[-2], path_parts[-1]
        try:
            issue_number = int(number_str)
        except ValueError:
            log.error("Cannot parse issue number: %s", number_str)
            sys.exit(1)

        resp = gh.get(f"{GITHUB_API_BASE}/repos/{owner}/{repo}/issues/{issue_number}")
        resp.raise_for_status()
        issue = resp.json()
        issue["bounty_info"] = extract_bounty_info(
            f"{issue.get('title', '')}\n{issue.get('body', '')}"
        )
        issues = [issue]
    else:
        log.info("Searching for bounty issues...")
        candidates = search_bounty_issues(gh, limit=args.limit * 3, extra_query=args.query)
        issues = filter_bounty_issues(candidates)

        if args.min_bounty > 0:
            filtered = []
            for iss in issues:
                bi = iss.get("bounty_info", {})
                amt = bi.get("amount")
                if amt:
                    try:
                        if float(amt) >= args.min_bounty:
                            filtered.append(iss)
                    except ValueError:
                        filtered.append(iss)
                else:
                    filtered.append(iss)
            issues = filtered
            log.info("After min-bounty filter: %d issues", len(issues))

        issues = issues[: args.limit]

    if not issues:
        log.info("No matching issues found")
        sys.exit(0)

    log.info("Will process %d issues", len(issues))

    success_count = 0
    for idx, issue in enumerate(issues, 1):
        log.info("\n[%d/%d]", idx, len(issues))
        try:
            if process_single_issue(gh, codex, issue, dry_run=args.dry_run):
                success_count += 1
        except Exception as exc:
            log.error("Error processing issue: %s", exc, exc_info=args.verbose)
            continue

    log.info("\n" + "=" * 60)
    log.info("Done! Successfully processed %d/%d issues", success_count, len(issues))
    log.info("Output directory: %s/", OUTPUT_DIR)

    if args.dry_run:
        log.info("\n*** DRY-RUN mode: No branches or PRs were actually created.")
        log.info("    Review outputs in %s/ then re-run with --issue to submit.", OUTPUT_DIR)


if __name__ == "__main__":
    main()
